//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Categories_Id { get; set; }
        public Nullable<int> Author_Id { get; set; }
        public string PrıntıngYear { get; set; }
        public string Publısher { get; set; }
        public string PagesNumber { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Movement Movement { get; set; }
    }
}
