//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empyloyees
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Personel Adı Boş Geçilemez")]
        //veri tabanı sınırlandırması için kullanılır.
        public string Employee { get; set; }
    }
}
