//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri_Listesi
    {
        public int ID { get; set; }
        public System.DateTime GirisTarihi { get; set; }
        public System.DateTime CikisTarihi { get; set; }
        public Nullable<int> KonoklamaSuresi { get; set; }
        public int OdaNumarası { get; set; }
        public Nullable<decimal> OdenecekUcret { get; set; }
        public int Musteriler_ID { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual OdaBilgisi OdaBilgisi { get; set; }
    }
}
