//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public int ID { get; set; }
        public string KullanıcıAdi { get; set; }
        public string Sifre { get; set; }
        public string Mail { get; set; }
    
        public virtual Personel_Listesi Personel_Listesi { get; set; }
    }
}
